/*
  Fetch full Vietnam address data (provinces -> districts -> wards) and
  generate src/data/vietnamAddressesData.ts for offline usage.
*/

const https = require('https');
const fs = require('fs');
const path = require('path');

const API_LIST_PROVINCES = 'https://provinces.open-api.vn/api/p/';
const ALLOW_INSECURE = process.env.ALLOW_INSECURE === '1';

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    const agent = new https.Agent({ rejectUnauthorized: !ALLOW_INSECURE });
    const request = https.get(url, { agent }, (res) => {
        // Follow redirects
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          const nextUrl = res.headers.location.startsWith('http')
            ? res.headers.location
            : new URL(res.headers.location, url).toString();
          res.resume();
          fetchJson(nextUrl).then(resolve).catch(reject);
          return;
        }
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}`));
          res.resume();
          return;
        }
        let data = '';
        res.on('data', (chunk) => (data += chunk));
        res.on('end', () => {
          try {
            resolve(JSON.parse(data));
          } catch (e) {
            reject(e);
          }
        });
      });
    request.on('error', reject);
  });
}

function escapeTsString(s) {
  return String(s).replace(/`/g, '\\`');
}

async function main() {
  console.log('Fetching full address data...');
  const provinces = await fetchJson(API_LIST_PROVINCES);

  const provincesData = provinces.map((p) => ({
    code: String(p.code),
    name: String(p.name),
  }));

  const districtsData = [];
  const wardsData = [];

  // Fetch districts+wards per province (depth=2)
  for (const p of provinces) {
    const provinceCode = String(p.code);
    const detailUrl = `https://provinces.open-api.vn/api/p/${provinceCode}?depth=2`;
    try {
      const provinceDetail = await fetchJson(detailUrl);
      if (Array.isArray(provinceDetail.districts)) {
        for (const d of provinceDetail.districts) {
          const districtCode = String(d.code);
          districtsData.push({
            code: districtCode,
            name: String(d.name),
            province_code: provinceCode,
          });
          // Fetch wards for each district
          try {
            const districtDetail = await fetchJson(`https://provinces.open-api.vn/api/d/${districtCode}?depth=2`);
            if (Array.isArray(districtDetail.wards)) {
              for (const w of districtDetail.wards) {
                wardsData.push({
                  code: String(w.code),
                  name: String(w.name),
                  district_code: districtCode,
                });
              }
            }
          } catch (e) {
            console.warn(`  Failed to fetch district ${districtCode}:`, e.message || e);
          }
        }
      }
    } catch (e) {
      console.warn(`Failed to fetch province ${provinceCode}:`, e.message || e);
    }
  }

  const outPath = path.join(__dirname, '..', 'src', 'data', 'vietnamAddressesData.ts');
  const header = `// Auto-generated by scripts/generateVietnamAddresses.js
// Do not edit manually. Regenerate with: npm run generate:addresses

export interface ProvinceDataItem { code: string; name: string; }
export interface DistrictDataItem { code: string; name: string; province_code: string; }
export interface WardDataItem { code: string; name: string; district_code: string; }
`;

  const provincesTs = 'export const provincesData: ProvinceDataItem[] = [\n' +
    provincesData
      .map((p) => `  { code: "${escapeTsString(p.code)}", name: "${escapeTsString(p.name)}" },`)
      .join('\n') +
    '\n];\n';

  const districtsTs = 'export const districtsData: DistrictDataItem[] = [\n' +
    districtsData
      .map(
        (d) =>
          `  { code: "${escapeTsString(d.code)}", name: "${escapeTsString(
            d.name
          )}", province_code: "${escapeTsString(d.province_code)}" },`
      )
      .join('\n') +
    '\n];\n';

  const wardsTs = 'export const wardsData: WardDataItem[] = [\n' +
    wardsData
      .map(
        (w) =>
          `  { code: "${escapeTsString(w.code)}", name: "${escapeTsString(
            w.name
          )}", district_code: "${escapeTsString(w.district_code)}" },`
      )
      .join('\n') +
    '\n];\n';

  const fileContent = [header, provincesTs, districtsTs, wardsTs].join('\n');

  fs.writeFileSync(outPath, fileContent, 'utf8');
  console.log(`Wrote ${provincesData.length} provinces, ${districtsData.length} districts, ${wardsData.length} wards to ${outPath}`);
}

main().catch((err) => {
  console.error('Failed to generate address data:', err);
  process.exit(1);
});


